"""Access PoPE-aware similarity and attention helpers.

(AI generated docstring)

You can use this module to compute PoPE similarity matrices and full attention outputs with either a
pure PyTorch fallback or the custom Triton kernels. The functions in this module sit directly on top
of `apply_pope_to_qk` and the paper's efficient Cartesian implementation of `Re(qᴴ k)` [1].

Contents
--------
Variables
	TRITON_AVAILABLE
		Report whether the optional Triton PoPE kernels imported successfully.

Functions
	compute_attn_similarity
		Compute a PoPE similarity matrix with a Triton fast path when available.
	compute_attn_similarity_non_fused
		Compute a PoPE similarity matrix with pure PyTorch tensor operations.
	flash_attn_with_pope
		Compute full attention outputs using PoPE-transformed queries and keys.

References
----------
[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
	(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding. Local
	project manuscript at `Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
"""

from __future__ import annotations

from einops import rearrange, repeat
from PoPE_pytorch import PolarEmbedReturn
from PoPE_pytorch.pope import apply_pope_to_qk
from torch import Tensor
from torch_einops_kit import and_masks, default, divisible_by, exists
import torch
import torch.nn.functional as F

try:
	from .triton_pope import triton_compute_qk_similarity
	from .triton_pope_flash_attn import flash_attn

	TRITON_AVAILABLE = True
except ImportError:
	TRITON_AVAILABLE = False

def compute_attn_similarity_non_fused(q: Tensor, k: Tensor, pope: PolarEmbedReturn, *, head_dimension_at_first: bool = True) -> Tensor:
	"""Compute the PoPE similarity matrix without Triton kernels.

	(AI generated docstring)

	This function provides the reference PoPE similarity path. The function converts `q` and `k` to
	the Cartesian PoPE representation with `apply_pope_to_qk`, expands grouped-query keys when
	necessary, and performs the final contraction with `torch.einsum`.

	Parameters
	----------
	q : Tensor
		Query tensor shaped either `(batch, heads, seq, dim)` or `(batch, seq, heads, dim)`.
	k : Tensor
		Key tensor with the same layout convention as `q`.
	pope : tuple[Tensor, Tensor]
		PoPE phases and biases generated by a PoPE module.
	head_dimension_at_first : bool = True
		Interpret `q` and `k` as head-first tensors when `True`.

	Returns
	-------
	similarity : Tensor
		Attention similarity tensor with shape `(batch, heads, q_len, k_len)`.

	See Also
	--------
	compute_attn_similarity : Select between this reference path and the Triton fast path.
	separate.pope.apply_pope_to_qk : Materialize the PoPE Cartesian representation.

	Paper Mapping
	-------------
	After `apply_pope_to_qk` materializes `x_q`, `y_q`, `x_k`, and `y_k`, the Einstein sum evaluates
	`∑_c x_q x_k + y_q y_k`, which is the real-valued PoPE similarity from the paper's efficient
	implementation section [1].

	References
	----------
	[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
		(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding.
		Local project manuscript at
		`Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
	"""
	if not head_dimension_at_first:
		q = rearrange(q, 'b n h d -> b h n d')
		k = rearrange(k, 'b n h d -> b h n d')

	q, k = apply_pope_to_qk(pope, q, k, to_magnitude=F.softplus)

	# group query attention support

	groups = q.shape[1] // k.shape[1]
	k = repeat(k, 'b h ... -> b (g h) ...', g=groups)

	return torch.einsum('b h i d, b h j d -> b h i j', q, k)

def compute_attn_similarity(
	q: Tensor, k: Tensor, pope: PolarEmbedReturn, *, allow_tf32: bool = True, head_dimension_at_first: bool = True
) -> Tensor:
	"""Compute a PoPE similarity matrix with a Triton fast path when available.

	(AI generated docstring)

	This function selects the custom Triton kernel when CUDA tensors and the optional extension are
	available, otherwise the function falls back to `compute_attn_similarity_non_fused`. The
	mathematical result is the same in both cases; only the execution strategy changes.

	Parameters
	----------
	q : Tensor
		Query tensor shaped either `(batch, heads, seq, dim)` or `(batch, seq, heads, dim)`.
	k : Tensor
		Key tensor with the same layout convention as `q`.
	pope : tuple[Tensor, Tensor]
		PoPE phases and biases generated by a PoPE module.
	allow_tf32 : bool = True
		Permit TensorFloat-32 matrix instructions in the Triton kernel.
	head_dimension_at_first : bool = True
		Interpret `q` and `k` as head-first tensors when `True`.

	Returns
	-------
	similarity : Tensor
		Attention similarity tensor with shape `(batch, heads, q_len, k_len)`.

	Raises
	------
	AssertionError
		Raised when grouped-query attention ratios are invalid or when `head_dim` is unsupported by
		the Triton kernel family.

	See Also
	--------
	compute_attn_similarity_non_fused : Reference implementation used for the fallback path.
	separate.triton_pope.triton_compute_qk_similarity : Triton implementation used for the CUDA fast
	path.

	Paper Mapping
	-------------
	This function computes the paper's PoPE similarity `∑_c μ_q μ_k cos((s − t) θ_c + δ_c)` [1]. The
	Triton branch implements the paper's efficient Cartesian decomposition, while the fallback branch
	keeps the same algebra in ordinary PyTorch tensor operations.

	References
	----------
	[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
		(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding.
		Local project manuscript at
		`Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
	"""
	q_heads: int = q.shape[1 if head_dimension_at_first else 2]
	k_heads: int = k.shape[1 if head_dimension_at_first else 2]
	if not divisible_by(q_heads, k_heads):
		message: str = f"I received `{q_heads = }` and `{k_heads = }`, but I need `q_heads` to be divisible by `k_heads` for grouped-query attention."
		raise ValueError(message)

	freqs, bias = pope
	head_dim: int = q.shape[-1]

	common_head_dims: tuple[int, ...] = (32, 48, 64, 128, 256)
	if head_dim not in common_head_dims:
		message: str = f"I received `{head_dim = }`, but I need `head_dim` to be one of `{common_head_dims = }` for the Triton kernel family."
		raise ValueError(message)

	is_cuda: bool = q.is_cuda and k.is_cuda and freqs.is_cuda and bias.is_cuda

	if TRITON_AVAILABLE and is_cuda:
		if not head_dimension_at_first:
			q = rearrange(q, 'b n h d -> b h n d')
			k = rearrange(k, 'b n h d -> b h n d')

		rotate_dim: int = freqs.shape[-1]
		return triton_compute_qk_similarity(q, k, freqs, bias, rotate_dim, allow_tf32=allow_tf32)

	return compute_attn_similarity_non_fused(q, k, pope, head_dimension_at_first=head_dimension_at_first)

def flash_attn_with_pope(
	q: Tensor,
	k: Tensor,
	v: Tensor,
	pos_emb: PolarEmbedReturn,
	*,
	mask: Tensor | None = None,
	causal: bool = False,
	softmax_scale: float | None = None,
	fused: bool | None = None,
	head_dimension_at_first: bool = True,
	dropout: float = 0.0,
) -> Tensor:
	"""Compute full attention outputs using PoPE-transformed queries and keys.

	(AI generated docstring)

	This function combines the paper's PoPE similarity with value aggregation. The function
	dispatches to the custom fused Triton attention kernel when that path is available, and otherwise
	applies PoPE explicitly before delegating to `torch.nn.functional.scaled_dot_product_attention`.

	Parameters
	----------
	q : Tensor
		Query tensor shaped either `(batch, heads, seq, dim)` or `(batch, seq, heads, dim)`.
	k : Tensor
		Key tensor with the same layout convention as `q`.
	v : Tensor
		Value tensor with the same layout convention as `q`.
	pos_emb : tuple[Tensor, Tensor]
		PoPE phases and biases generated by a PoPE module.
	mask : Tensor | None = None
		Optional key padding mask.
	causal : bool = False
		Apply causal masking.
	softmax_scale : float | None = None
		Explicit softmax scale. When `None`, the function uses `q.shape[-1] ** -0.5`.
	fused : bool | None = None
		Select the Triton fused kernel explicitly. When `None`, the function chooses a default based
		on availability and device placement.
	head_dimension_at_first : bool = True
		Interpret `q`, `k`, and `v` as head-first tensors when `True`.
	dropout : float = 0.
		Attention dropout probability.

	Returns
	-------
	output : Tensor
		Attention output tensor with the same layout convention as `q`.

	See Also
	--------
	compute_attn_similarity : Return only the similarity matrix.
	separate.triton_pope_flash_attn.flash_attn : Fused Triton implementation used by the fast path.

	Paper Mapping
	-------------
	The fused branch implements the paper's efficient PoPE attention strategy [1] by evaluating the
	Cartesian real part of `qᴴ k` inside the attention kernel. The fallback branch materializes the
	same PoPE-transformed `q` and `k`, then uses standard scaled dot-product attention for the
	softmax and value-weighted aggregation steps.

	References
	----------
	[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
		(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding.
		Local project manuscript at
		`Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
	"""
	seq_dim: int = 2 if head_dimension_at_first else 1
	q_len, kv_len, device = q.shape[seq_dim], k.shape[seq_dim], q.device

	fused = default(fused, TRITON_AVAILABLE and q.is_cuda)

	softmax_scale = default(softmax_scale, q.shape[-1] ** -0.5)

	if fused:
		# fused kernel expects (batch, seq, heads, dim)

		if head_dimension_at_first:
			q = rearrange(q, 'b h n d -> b n h d')
			k = rearrange(k, 'b h n d -> b n h d')
			v = rearrange(v, 'b h n d -> b n h d')

		freqs, bias = pos_emb
		out: Tensor = flash_attn(
			q, k, v, freqs=freqs, pope_bias=bias, mask=mask, causal=causal, softmax_scale=softmax_scale, dropout=dropout
		)

		if head_dimension_at_first:
			out = rearrange(out, 'b n h d -> b h n d')

		return out

	# non-fused manual path
	# standardize to (batch, heads, seq, dim)

	if not head_dimension_at_first:
		q = rearrange(q, 'b n h d -> b h n d')
		k = rearrange(k, 'b n h d -> b h n d')
		v = rearrange(v, 'b n h d -> b h n d')

	q, k = apply_pope_to_qk(pos_emb, q, k, to_magnitude=F.softplus)

	# group query attention support

	groups: int = q.shape[1] // k.shape[1]
	k = repeat(k, 'b h ... -> b (g h) ...', g=groups)
	v = repeat(v, 'b h ... -> b (g h) ...', g=groups)

	# manual attention path using SDPA
	# ensure dtypes match for SDPA (apply_pope_to_qk might have upcasted to float32)

	v_dtype: torch.dtype = v.dtype
	v_dim: int = v.shape[-1]

	if q.dtype != v.dtype:
		v = v.to(q.dtype)

	attn_mask: Tensor | None = None
	if exists(mask):
		attn_mask = rearrange(mask, 'b j -> b 1 1 j')

	if causal and (q_len < kv_len or exists(attn_mask)):
		causal_mask: Tensor = torch.ones((q_len, kv_len), dtype=torch.bool, device=device).tril(diagonal=kv_len - q_len)
		attn_mask = and_masks([attn_mask, causal_mask])
		causal = False

	out = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask, is_causal=causal, scale=softmax_scale, dropout_p=dropout)

	# mps sdpa bug (pytorch 2.9.1) - output takes q/k dim instead of v dim
	# first v_dim elements are correct, so slicing suffices
	# only triggers in no_grad (inference). todo - remove once fixed upstream

	if out.shape[-1] != v_dim:
		out = out[..., :v_dim]

	out = out.to(v_dtype)

	if not head_dimension_at_first:
		out = rearrange(out, 'b h n d -> b n h d')

	return out
