"""Access one-dimensional Polar Coordinate Positional Embedding primitives.

(AI generated docstring)

You can use this module to instantiate the one-dimensional PoPE construction from the paper and to
transform raw query and key tensors into the Cartesian representation consumed by the attention code.
The module covers the geometric frequency schedule, the learnable key-side bias, and the rotation
logic that removes the RoPE what-where interaction term [1].

Contents
--------
Functions
	apply_pope_to_qk
		Transform raw query and key tensors into PoPE-rotated representations.

Classes
	PoPE
		Parameterize per-head PoPE frequencies and learnable phase biases.

References
----------
[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
	(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding. Local
	project manuscript at `Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
"""

from __future__ import annotations

from collections.abc import Callable
from einops import einsum, rearrange
from math import pi
from PoPE_pytorch import PolarEmbedReturn
from torch import arange, cat, is_tensor, Tensor
from torch._prims_common import DeviceLikeType
from torch.amp.autocast_mode import autocast
from torch.nn import Module, Parameter
from torch_einops_kit import exists, slice_right_at_dim
from typing import cast
import torch
import torch.nn.functional as F

@autocast('cuda', enabled=False)
def apply_pope_to_qk(
	pope: PolarEmbedReturn, q: Tensor, k: Tensor, to_magnitude: Callable[..., Tensor] = F.softplus, *, return_complex: bool = False
) -> tuple[Tensor, Tensor]:
	"""Transform query and key tensors into PoPE-rotated representations.

	(AI generated docstring)

	This function implements the paper's conversion from real-valued query and key features to
	non-negative magnitudes with position-dependent phases [1]. The function applies `to_magnitude`
	to the rotated prefix, combines `freqs` with the learned key-side bias, and emits either a
	doubled real Cartesian representation or a complex-valued representation.

	Parameters
	----------
	pope : PolarEmbedReturn
		PoPE phases and per-head biases generated by `PoPE.forward`.
	q : Tensor
		Query tensor whose penultimate dimension is the query sequence dimension.
	k : Tensor
		Key tensor whose penultimate dimension is the key sequence dimension.
	to_magnitude : Callable[..., Tensor] = F.softplus
		Function used to map raw features to non-negative magnitudes.
	return_complex : bool = False
		Return complex numbers instead of the doubled real Cartesian form.

	Returns
	-------
	rotatedQuery : Tensor
		PoPE-transformed representation of `q`.
	rotatedKey : Tensor
		PoPE-transformed representation of `k`.

	Raises
	------
	AssertionError
		Raised when `q` is longer than `k`, or when the rotated dimension exceeds the feature
		dimension of `q` and `k`.

	See Also
	--------
	PoPE.forward : Generate the `pope` tuple consumed by this function.
	separate.attention.compute_attn_similarity : Consume the returned Cartesian form to compute PoPE
	similarities.

	Mathematical Basis
	------------------
	Let `μ_q = to_magnitude(q)` and `μ_k = to_magnitude(k)`. For each rotated feature `c`, the query
	phase is `t θ_c` and the key phase is `s θ_c + δ_c`. When `return_complex` is `False`, the
	function returns the Cartesian pair `[μ cos(ϕ), μ sin(ϕ)]` so downstream kernels can accumulate
	`x_q x_k + y_q y_k`, which is exactly the real part of `qᴴ k` used in the paper's efficient
	implementation section [1].

	References
	----------
	[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
		(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding.
		Local project manuscript at
		`Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
	"""
	freqs, bias = pope

	q_len, k_len, qk_dim, rotate_dim = q.shape[-2], k.shape[-2], q.shape[-1], freqs.shape[-1]

	if q_len > k_len:
		message: str = f'I received `{q_len = }` and `{k_len = }`, but I need `q_len <= k_len`.'
		raise ValueError(message)

	if rotate_dim > qk_dim:
		message: str = f'I received `{rotate_dim = }` and `{qk_dim = }`, but I need `rotate_dim <= qk_dim`.'
		raise ValueError(message)

	is_partial_rotate: bool = rotate_dim < qk_dim

	if is_partial_rotate:
		q, q_rest = q[..., :rotate_dim], q[..., rotate_dim:]
		k, k_rest = k[..., :rotate_dim], k[..., rotate_dim:]

		if return_complex:
			q_rest: Tensor = torch.polar(q_rest, torch.zeros_like(q_rest))
			k_rest: Tensor = torch.polar(k_rest, torch.zeros_like(k_rest))

	if freqs.ndim == 3:
		freqs: Tensor = rearrange(freqs, 'b n d -> b 1 n d')

	freqs_with_bias: Tensor = freqs + rearrange(bias, 'h d -> h 1 d')

	# convert q and k to polar magnitudes with activation

	q, k = to_magnitude(q), to_magnitude(k)

	# apply rotations

	freqs = slice_right_at_dim(freqs, q_len, dim=-2)

	if return_complex:
		q = torch.polar(q, freqs)
	else:
		qcos, qsin = freqs.cos(), freqs.sin()
		q = rearrange([q * qcos, q * qsin], 'two ... d -> ... (d two)')

	# handle inference

	if return_complex:
		k = torch.polar(k, freqs_with_bias)
	else:
		kcos, ksin = freqs_with_bias.cos(), freqs_with_bias.sin()
		k = rearrange([k * kcos, k * ksin], 'two ... d -> ... (d two)')

	# concat

	if is_partial_rotate:
		q = cat((q, q_rest), dim=-1)
		k = cat((k, k_rest), dim=-1)

	return q, k

class PoPE(Module):
	"""Instantiate learnable one-dimensional PoPE embeddings for attention heads.

	(AI generated docstring)

	You can use this module to parameterize the PoPE frequency schedule and the learnable key-side
	phase bias from the paper [1]. `PoPE` stores the component-specific frequencies `θ_c` and the
	per-head bias `δ_c`, then materializes a `tuple[Tensor, Tensor]` for a requested sequence of
	positions.

	Parameters
	----------
	dim : int
		Number of rotated feature dimensions.
	heads : int
		Number of attention heads sharing the same frequency schedule but using independent key-side
		biases.
	theta : float = 10000
		Base wavelength used for the geometric frequency schedule.
	bias_uniform_init : bool = False
		Initialize `bias` from `Uniform(-2π, 0)` instead of zero.
	inv_freqs : Tensor | list[float] | None = None
		Explicit inverse-frequency schedule. When `None`, the schedule is built from `theta`.

	Attributes
	----------
	inv_freqs : Tensor
		Registered buffer containing the one-dimensional PoPE frequency schedule.
	bias : Parameter
		Learnable per-head phase offsets implementing the biased PoPE variant.

	See Also
	--------
	apply_pope_to_qk : Convert raw query and key tensors into the PoPE representation.
	separate.attention.flash_attn_with_pope : Consume the output of `forward` inside an attention
	layer.

	Paper Mapping
	-------------
	The buffer `inv_freqs` corresponds to the component-specific frequency bank `θ_c` in the PoPE
	construction. The parameter `bias` corresponds to the learnable offset `δ_c` in the biased
	similarity `∑_c μ_q μ_k cos((s − t) θ_c + δ_c)` discussed in Equation `pope-bias` [1].

	References
	----------
	[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
		(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding.
		Local project manuscript at
		`Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
	"""

	apply_pope_to_qk = staticmethod(apply_pope_to_qk)

	def __init__(
		self, dim: int, *, heads: int, theta: float = 10000, bias_uniform_init: bool = False, inv_freqs: Tensor | None = None
	) -> None:
		super().__init__()

		if not exists(inv_freqs):
			inv_freqs = theta ** -(arange(dim).float() / dim)

		self.register_buffer('inv_freqs', inv_freqs)

		# the learned bias on the keys

		self.bias = Parameter(torch.zeros(heads, dim))

		if bias_uniform_init:
			self.bias.uniform_(-2.0 * pi, 0.0)

	@property
	def device(self) -> DeviceLikeType:
		"""Retrieve the device hosting the PoPE frequency buffer.

		(AI generated docstring)

		This property exposes the device used by `inv_freqs` so callers can create position tensors
		that are already aligned with the PoPE parameters.

		Returns
		-------
		device : DeviceLikeType
			Device holding `inv_freqs`.
		"""
		return cast(Tensor, self.inv_freqs).device

	@autocast('cuda', enabled=False)
	def forward(self, pos_or_seq_len: Tensor | int, offset: int = 0) -> PolarEmbedReturn:
		"""Generate PoPE frequencies and biases for sequence positions.

		(AI generated docstring)

		This method accepts either explicit positions or a sequence length, constructs the phase
		tensor for each rotated feature, and returns the clamped key-side bias needed by
		`apply_pope_to_qk` and the attention kernels.

		Parameters
		----------
		pos_or_seq_len : Tensor | int
			Explicit positions or the total sequence length.
		offset : int = 0
			Offset added to every position before phase construction.

		Returns
		-------
		polarEmbed : PolarEmbedReturn
			Tuple containing the phase tensor and the clamped per-head bias tensor.

		See Also
		--------
		apply_pope_to_qk : Consume the returned tuple to rotate query and key tensors.

		Mathematical Basis
		------------------
		Let `pos` denote the absolute position tensor after adding `offset`. The method forms
		`freqs[..., i, c] = pos[..., i] θ_c`, which supplies the position-dependent phase terms in
		Equation `pope`. The method also clamps `bias` to `[-2π, 0]`, matching the stability
		heuristic described for the biased PoPE variant [1].

		References
		----------
		[1] Gopalakrishnan, A., Csordás, R., Schmidhuber, J., and Mozer, M. C.
			(2026). Decoupling the ``What'' and ``Where'' With Polar Coordinate Positional Embedding.
			Local project manuscript at
			`Z0Z_notes/Polar_Coordinate_Positional_Embedding/iclr2026_conference.tex`.
		"""
		# get positions depending on input

		if is_tensor(pos_or_seq_len):
			pos: Tensor = pos_or_seq_len
		else:
			seq_len: int = pos_or_seq_len
			pos = arange(seq_len, device=self.device, dtype=cast(Tensor, self.inv_freqs).dtype)

		pos = pos + offset

		# freqs

		freqs: Tensor = einsum(pos, cast(Tensor, self.inv_freqs), '... i, j -> ... i j')

		# the bias, with clamping

		bias: Tensor = self.bias.clamp(-2.0 * pi, 0.0)

		return PolarEmbedReturn(freqs, bias)
